refactor event and gui element registering
- if the constructor invocation throws exception or any of the classes fail initialization with e.g NoClassDefFoundError the mod will now continue registering other elements, whereas before it would not.
- its now verified that event listeners have at least 1 method with SubscribeEvent
- gui elements now register separately and are not registered to the forge event bus unless required. its verified that they don't have any SubscribeEvent methods if they are not being registered to the forge event bus, so that not registering is safe.
- initGuiManager moved out of registerAll, no functional change